### ISSUE TITLE
"ReferenceError: primordials is not defined" on `npm install` (Quickstart guide)

### ISSUE THREAD

**Issue by quinncomendant** [gae-init/gae-init-upload#28]
I'm following the [Quickstart](http://docs.gae-init.appspot.com/quickstart/) on gae-init-upload commit f8bdff0 and getting this error when running `npm install`:

   ReferenceError: primordials is not defined

Below is the full output from the installer, and [here is the debug.log](https://write.as/gnlsfk9r883d3.txt).

```
[q@haywire/0 hello] npm install
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> fsevents@1.2.9 install /Users/q/src/hello/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/q/src/hello/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> husky@3.0.0 install /Users/q/src/hello/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> core-js-pure@3.1.4 postinstall /Users/q/src/hello/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> husky@3.0.0 postinstall /Users/q/src/hello/node_modules/husky
> opencollective-postinstall || true

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate


> gae-init@ install /Users/q/src/hello
> gulp init

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/q/src/hello/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/q/src/hello/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/vinyl-fs/lib/src/getContents/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/vinyl-fs/lib/src/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/vinyl-fs/index.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/node_modules/gulp/index.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/gulpfile.coffee:1:29)
    at Object.<anonymous> (/Users/q/src/hello/gulpfile.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.loadFile (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/Users/q/src/hello/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/q/src/hello/gulpfile.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Liftoff.handleArguments (/Users/q/src/hello/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/Users/q/src/hello/node_modules/liftoff/index.js:203:12)
    at module.exports (/Users/q/src/hello/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/q/src/hello/node_modules/liftoff/index.js:195:5)
    at /Users/q/src/hello/node_modules/liftoff/index.js:165:9
    at /Users/q/src/hello/node_modules/v8flags/index.js:110:14
    at /Users/q/src/hello/node_modules/v8flags/index.js:38:12
    at /Users/q/src/hello/node_modules/v8flags/index.js:49:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gae-init@ install: `gulp init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gae-init@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/q/.npm/_logs/2019-07-12T04_15_34_249Z-debug.log
```

**Comment by lipis** [comment]
Try `yarn install`

**Comment by quinncomendant** [comment]
Exactly the same with `yarn install`

**Comment by lipis** [comment]
What's your NPM version and Python?

**Comment by quinncomendant** [comment]
```
# npm -v
6.9.0
# python -V
Python 3.7.4
```

**Comment by lipis** [comment]
You should use Python 2.7..
